export class Exception{
    constructor(private status:'success'|'fail',private message:string){}
}